#!/bin/sh

### BEGIN INIT INFO
# Provides: Xvfb service
# Required-Start:
# Required-Stop:
# Default-Start:
# Default-Stop:
# Short-Description: Start transparentproxy
### END INIT INFO


# Required-Start:    $localdd_fs $syslog $remote_fs dbus
# Required-Stop:     $local_fs $syslog $remote_fs
# Default-Start:     3 4 5
# Default-Stop:      0 1 2 6

XVFB=/usr/bin/Xvfb
# XVFBARGS=":1 -screen 0 1024x768x24 -ac +extension GLX +render -noreset -nolisten tcp"
XVFBARGS=":99 -screen 5 1024x768x8"
PIDFILE=/var/run/xvfb.pid
case "$1" in
  start)
    echo -n "Starting virtual X frame buffer: Xvfb"
    start-stop-daemon --start --quiet --pidfile $PIDFILE --make-pidfile --background --exec $XVFB -- $XVFBARGS
    echo "."
    ;;
  stop)
    echo -n "Stopping virtual X frame buffer: Xvfb"
    start-stop-daemon --stop --quiet --pidfile $PIDFILE
    echo "."
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
        echo "Usage: /etc/init.d/xvfb {start|stop|restart}"
        exit 1
esac

exit 0
